travis:
  secure:
    BINSTAR_TOKEN: J9K4dYxDY/3F2TyK42fjA33b5shyXh7tc5NdQ/Fh+pmiBF7Rf5abgnA/3FerpPpPFeEa4pdJ+FJzk2u1ezMXB7EycDE+Wq7bnKUkmcRQ/bsp6MtTZD1FfwE4xaUf6ta2YxHuRaJ/l3zkkUd+JWYAE9DQHY9vitlKPF/vlK4vLI37kQT/8xPoe+8AuB0GnpoNqaGSQgEep8U+1xkN20fwvKPj1uwlNsmqRbWnhlmKO4eDAcSDr40GpxYR4GkvtLYHlN+mgFcAJ1ZYljootCtLA9pIx0MAjofz9d8z8mO3IShiKNVhORyWw/QW412SzzE2P3eqqw9MB6ybazwpUNhj29hcrLlCSmrmfksbdiJ1Ia8DzDx7Qe9//OQZ8UioR6886XFn5nRWtOVmHGOPAcojWERPIrs4hqBkOnrk+dUe69SpJ37rzQdpXWd1na8IqPc5YN6LzB0Cnckvn5Fc/K6SA12S/nXgJ3VdgFXQXSpM2uMa+VMzszO8aOd/VSDzDmrTMd/pt/KbAw25zdMVq8R1n3gG6Od344WP9DAoh9nsmTva5dZ3t5Y1XDEROd82gpTWWwIkXsm6FmrDQYhwMoSmdDOEVOId1U4eYkLFC0vn3ALkKezd3B1rF7e+5PXYzAo6xgxrYPopBexP9GawPPZIgX3npcBOUxLESHwmZynLHBk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
